"""
Note: if you outline rectangles this will not work
This combines PolygonExtractOutlineBlackObjects.py and PolygonCSVMakeSmallerExportImage.py
into one program.  This program will automatically look for pure black
in the image and extract the outline.  If there are multiple black objects it will
create multiple objects and save them as different polygons.  You can also try and
automatically outline objects using photoshop's "Select Subject".

Outlines were generated by using the Object Selection Tool in Photoshop to outline
the sections.  The images were converted to greyscale using “ConvertGreyscale.py”
and saved in .tif format using LZW compression.  They were then opened in Photoshop
and the outlines expanded 80 pixels using Select>Modify>Expand tool and filled with
black.  Any black boxes from the microscope images were filled with white using the
Paint Bucket tool and saved in .tif format with LZW compression.  The images were
then run using “PolygonExtractOutlineBlackObjectsv1.1b.py”.  This generated the .csv
files with polygon points and a PNG image of the outlined black objects and numbering.

This can go faster if you save the files as a jpg but you need to change the
code to open jpg files.

You can make a MBF outline file to upload using MBFMakeOutlines

Version 1.1  The script was taking too long for some images.  This adds an
called FoldDecrease which was originall set to 2.  If you increase it above
2 it will reduce the image size more before extracting the outline and
should speed things up.  It then increases the contour size afterwards to
compensate for the image size decrease.

V1.3 does not make an image if there are no values (preventing a NAN error).  It also
does not make a CSV file.  Allows you to change the minimum size (minsize) of polygon
extracted

V1.4 Makes the outline different colors and the number the same color on the PNG
image so it's easier to tell their are associated.

V1.4b made sure the PNG outlines were the same dimensions as the original TIF file

© 2023 Washington University in St. Louis
Non-commercial research use only.
See LICENSE.txt for full terms.
https://github.com/goochlab/CellQuantAI/blob/main/LICENSE.txt
"""

from PIL import Image, ImageDraw, ImageFont
import cv2
import numpy as np
import pandas as pd
import os
from tkinter import Tk
from tkinter.filedialog import askdirectory
import random  # Import random for color generation
import winsound  # Windows-specific sound notification

# Set the FoldDecrease variable to reduce image size before processing
FoldDecrease = 8

Percent = 0  # 0 means no image shrinkage, 50 means 50% reduction
CsvFile = "yes"
Imager = "yes"
minsize = 50  # Minimum size of polygon to extract outline Default = 50

# Open a window to select a folder
Tk().withdraw()
folder_path = askdirectory()
fold = folder_path
Image.MAX_IMAGE_PIXELS = None

# Dictionary to store original image sizes by base filename
image_sizes = {}

# Iterate through all the files in the selected folder
for filename in os.listdir(folder_path):
    if filename.startswith("._"):  # Ignore macOS metadata files
        continue
    if filename.endswith('.tif') or filename.endswith('.TIF'):
        print(filename)

        # Open the original image to get dimensions
        orig_image = Image.open(os.path.join(folder_path, filename))
        orig_width, orig_height = orig_image.size
        base_name = os.path.splitext(filename)[0]
        image_sizes[base_name] = (orig_width, orig_height)  # Save size

        # Convert to grayscale and resize for processing
        image = orig_image.convert('L')
        image = image.resize((orig_width // FoldDecrease, orig_height // FoldDecrease), Image.LANCZOS)

        # Convert to OpenCV format and threshold
        image = np.array(image)
        _, thresh = cv2.threshold(image, 0, 255, cv2.THRESH_BINARY_INV)

        # Find contours
        contours, _ = cv2.findContours(thresh, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

        # Create DataFrame for polygon coordinates
        df = pd.DataFrame(columns=['Polygon', 'X', 'Y'])

        # Process each contour
        for i, contour in enumerate(contours):
            polygon = [[point[0][0] * FoldDecrease, point[0][1] * FoldDecrease] for point in contour]
            polygon = np.array(polygon)

            # Draw polygon on image
            cv2.polylines(image, [polygon], True, (255, 255, 255), thickness=2)

            # Add polygon coordinates to DataFrame
            for point in polygon:
                new_row = pd.DataFrame({'Polygon': [i + 1], 'X': [point[0]], 'Y': [point[1]]})
                df = pd.concat([df, new_row], ignore_index=True)

        # Filter polygons by size
        df = df[df.groupby('Polygon')['Polygon'].transform('size') > minsize]

        # Save CSV file
        csv_filename = os.path.splitext(filename)[0] + 'P.csv'
        df.to_csv(os.path.join(folder_path, csv_filename), index=False)

for file in os.listdir(fold):
    if file.endswith('P.csv'):
        print(file)
        df = pd.read_csv(os.path.join(fold, file))
        os.remove(os.path.join(fold, file))  # Delete CSV after loading

        df['Polygon'] = df.groupby('Polygon').ngroup() + 1
        grouped = df.groupby('Polygon')

        # Create result DataFrame
        result = pd.DataFrame(columns=['Polygon', 'X', 'Y'])

        # Process each polygon
        for name, group in grouped:
            rows_per_part = 700
            parts = np.array_split(group, rows_per_part)

            for part in parts:
                avg = part.mean()
                result = pd.concat([result, pd.DataFrame([avg])], ignore_index=True)

        # Drop NaN values
        result.dropna(inplace=True)
        result['X'] = result['X'].astype(int)
        result['Y'] = result['Y'].astype(int)

        # Save processed CSV file
        if CsvFile == "yes" and not result.empty and not result.equals(pd.DataFrame(columns=['Polygon', 'X', 'Y'])):
            result.to_csv(os.path.join(fold, f'A{file}'), index=False)
            print(f"Saved result to A{file}")
        else:
            print("No values in 'X' column or data is empty. Not saving CSV file.")

        # Create PNG image with same dimensions as the original TIF
        try:
            base_file = file.replace('P.csv', '')
            if base_file in image_sizes:
                orig_width, orig_height = image_sizes[base_file]
                img = Image.new('RGBA', (orig_width, orig_height), (255, 255, 255, 255))
                draw = ImageDraw.Draw(img)

                # Load font for numbering
                font_size = int(500 * (1 - Percent / 100))
                try:
                    font = ImageFont.truetype('arial.ttf', font_size)
                except IOError:
                    font = ImageFont.load_default()  # Fallback in case font isn't found

                grouped_result = result.groupby('Polygon')

                # Draw polygons with numbered labels
                for name, group in grouped_result:
                    color = tuple(random.randint(0, 255) for _ in range(3)) + (255,)

                    draw.polygon(
                        list(zip(group['X'], group['Y'])),
                        outline=color,
                        width=5
                    )

                    # Draw number at the polygon center
                    center_x = group['X'].mean()
                    center_y = group['Y'].mean()
                    draw.text((center_x, center_y), str(name), fill=color, anchor='mm', font=font)

                # Save PNG image
                img.convert('RGB').save(os.path.join(fold, f'{base_file}.png'))
            else:
                print(f"Original size not found for {base_file}, skipping PNG.")
        except ValueError:
            print("Error: Unable to calculate max values.")

# Rename processed CSV files to remove the "A" prefix
for file in os.listdir(fold):
    if file.startswith("A") and file.endswith("P.csv"):
        old_path = os.path.join(fold, file)
        new_path = os.path.join(fold, file[1:])  # Remove the leading "A"
        os.rename(old_path, new_path)
        print(f"Renamed {file} to {file[1:]}")


# Beep sound notification (Windows only)
winsound.Beep(1000, 100)
winsound.Beep(1000, 100)
winsound.Beep(1000, 100)
